name: Send Changed YAML Files to Endpoint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'solutions/**/*.yml'

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git to fetch the PR base
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Find changed .yml files in solutions folder
        id: find_files
        run: |
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD -- 'solutions/*.yml')
          echo "$CHANGED_FILES" > changed_files.txt
          FILE_NAMES=""
          for file in $CHANGED_FILES; do
            FILE_NAMES+=$(basename "$file")$'\n'
          done
          echo "$FILE_NAMES" > filenames.txt

      - name: Send changed .yml files to endpoint and capture response
        if: steps.find_files.outputs.changed_files != ''
        id: send_request
        run: |
          RESPONSE=""
          TOKEN="${{ secrets.TEST_TOKEN }}"

          CHANGED_FILES=$(cat changed_files.txt)
          for file in $CHANGED_FILES; do
            FILE_NAME=$(basename "$file")
            FILE_NAME_BASE64=$(echo -n "$FILE_NAME" | base64)
            FILE_CONTENT_BASE64=$(cat "$file" | base64)

            RESPONSE_FILE=$(curl -X POST "https://write-you-d6a7evhclq-uc.a.run.app/public/test.php" \
              -d "filename=$FILE_NAME_BASE64" \
              -d "content=$FILE_CONTENT_BASE64" \
              -d "token=$TOKEN")
            
            RESPONSE+="Response for $FILE_NAME:\n$RESPONSE_FILE\n\n"
          done

          echo "$RESPONSE" > response.txt
