name: Send Changed YAML Files to Endpoint and Comment Response

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new PRs and updates to PRs (pushes)
    paths:
      - 'solutions/**/*.yml'  # Trigger only when .yml files in solutions/ are modified

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git to fetch the PR base
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Find changed .yml files in solutions folder
        id: find_files
        run: |
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD -- 'solutions/*.yml')
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Send changed .yml files to endpoint and capture response
        if: env.changed_files != ''
        id: send_request
        run: |
          RESPONSE=""
          TOKEN="${{ secrets.TEST_TOKEN }}"

          for file in $CHANGED_FILES; do
            FILE_NAME=$(basename "$file")
            FILE_NAME_BASE64=$(echo -n "$FILE_NAME" | base64)
            FILE_CONTENT_BASE64=$(cat "$file" | base64)

            RESPONSE_FILE=$(curl -X POST "https://write-you-d6a7evhclq-uc.a.run.app/public/test.php" \
              -d "filename=$FILE_NAME_BASE64" \
              -d "content=$FILE_CONTENT_BASE64" \
              -d "token=$TOKEN")
            
            RESPONSE+="Response for $FILE_NAME:\n$RESPONSE_FILE\n\n"
          done

          echo "response=$RESPONSE" >> $GITHUB_ENV
