name: Send Changed YAML Files to Test Endpoint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'solutions/**/*.yml'

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git to fetch the PR base
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Send changed .yml files to test endpoint
        id: send_changed_files
        env:
          TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          BASE_BRANCH=$(jq -r '.pull_request.base.ref' < $GITHUB_EVENT_PATH)
          git fetch origin $BASE_BRANCH
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD -- 'solutions/**/*.yml')

          if [ -z "$CHANGED_FILES" ]; then
            echo "No solutions .yml files found."
            exit 0
          fi

          for file in $CHANGED_FILES; do
            FILE_NAME=$(basename "$file")
            FILE_NAME_BASE64=$(echo -n "$FILE_NAME" | base64)
            FILE_CONTENT_BASE64=$(base64 -w 0 "$file")

            RESPONSE=$(curl -s -X POST "https://write-you-d6a7evhclq-uc.a.run.app/test.php" \
              -d "filename=$FILE_NAME_BASE64" \
              -d "content=$FILE_CONTENT_BASE64" \
              -d "token=$TOKEN")

            OK=$(echo "$RESPONSE" | jq -r '.ok')
            if [ "$OK" == "false" ]; then
              echo "API response indicated failure: $RESPONSE"
              exit 1
            fi

            echo "Response for $file: $RESPONSE"
          done
